#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>
#include <vcruntime.h>
#include <assert.h>
#include <stdio.h>
#include <stdbool.h>
#include <mbstring.h>
#include <stdarg.h>
#include <combaseapi.h>
#include <errno.h>
#include <stdlib.h>
#include <io.h>
#include <direct.h>